### PR TITLE
CANVAS-143 - upgrade webpack to v5

### PR DESCRIPTION
**Pull request by jackvanb**
Upgrade webpack to v5. See [ucla/lti-media-resources#376](https://github.com/ucla/lti-media-resources/pull/376) for details.

### CODE REVIEW

**Comment by rlorenzo** [comment]
@jackvanb For some reason, this is not working for me. I am using NodeJS 14.15.5 and when I do production mode and yarn start I get this error:

ERROR in ./node_modules/@instructure/ui-toggle-details/lib/ToggleGroup/index.js 48:16-67
Module not found: Error: Package path ./lib/testable.js is not exported from package /Users/rex/Projects/lti-course-requestor/node_modules/@instructure/ui-testable (see exports field in /Users/rex/Projects/lti-course-requestor/node_modules/@instructure/ui-testable/package.json)
 @ ./node_modules/@instructure/ui-toggle-details/lib/index.js 21:14-47
 @ ./src/client/indexform/index.js 26:23-64
 @ ./src/client/App/index.js 14:36-68
 @ ./src/client/index.js 9:36-61

webpack 5.24.1 compiled with 223 errors in 9150 ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lti-course-requestor@1.0.0 build: `webpack --mode production`
npm ERR! Exit status 1

**Comment by rlorenzo** [comment]
@jackvanb Similar to upgrading the html-webpack-plugin plugin, do we also need to update css-loader (https://github.com/ucla/lti-course-requestor/pull/327)?

**Comment by jackvanb** [comment]
@rlorenzo Updating instructure-ui and loaders didn't fix the issue. Will have to debug further

**Comment by jackvanb** [comment]
@rlorenzo Found out the issue is caused by the @instructure/ui-babel-preset package. After removing it, the code compiles. Is it safe to remove this?

**Comment by rlorenzo** [comment]
@jackvanb  If you remove it does the app still load and work?

**Comment by jackvanb** [comment]
@rlorenzo App still loaded and worked fine after removing

**Comment by jackvanb** [comment]
I guess it was needed as a polyfill for the jest tests. Added @babel/plugin-transform-runtime to fix this, which is used in the other 2 React apps

**Comment by rlorenzo** [comment]
Now loads for me

**Pull request merged**
